### PR TITLE
Update to kamal-proxy 0.8.0

### PR DESCRIPTION
**Pull request by djmb**
Proxy changes:
- Add option to use custom TLS certificates (#17)
- Don't buffer SSE responses (#36)
- Allow routing to wildcard subdomains (#45)

Custom TLS certificates not supported in Kamal itself yet. Buffering SSE responses and wildcard subdomains will work without any Kamal changes.

### CODE REVIEW

**Comment by karls** [comment]
I didn't want to create a new issue, so commenting in here. Am I correct that currently there is no way to specify the `kamal-proxy` version without a code change in Kamal itself?

**Comment by tuladhar** [comment]
> I didn't want to create a new issue, so commenting in here. Am I correct that currently there is no way to specify the `kamal-proxy` version without a code change in Kamal itself?

@karls That's correct, it's currently hardcoded in the code. 

https://github.com/basecamp/kamal/blob/e34031f70cf933384fe0467ade20d6653f3ea908/lib/kamal/configuration.rb#L17

**Comment by tuladhar** [comment]
> @karls I was about to ask the same question, you beat me to it :D. FWIW: I was looking in the CLI commands for a `kamal proxy upgrade`.

I discovered that you can upgrade the Kamal Proxy using the following command:
```
kamal proxy reboot
```

If it's running old version, and new version is available, then it will upgrade, e.g:
>  ERROR (RuntimeError): Exception while executing on host certsdiscount-app1: kamal-proxy version v0.6.0 is too old, please reboot to update to at least v0.7.0

**Comment by paganotoni** [comment]
thanks @tuladhar. I tried rebooting. however, it did not work.

**Comment by tuladhar** [comment]
> thanks @tuladhar. I tried rebooting. however, it did not work.

Same here. I tried rebooting again, but it didn’t update beyond what’s hardcoded in the code.

**Comment by djmb** [comment]
Yes right now the version is fixed entirely. But I think we'll allow updating to later versions, or running your own image if you want to fork kamal-proxy

**Pull request merged**
