### PR TITLE
Fix redeploy command missing registry authentication

### PR DESCRIPTION
**Pull request by tonysm**
### Fixed

- Fixes the redeploy command missing registry authentication

### CODE REVIEW

**Comment by dhh** [comment]
This is by design. Point of redeploy over deploy is to do fewer steps that aren't necessary when repeatedly deploying.

**Comment by tonysm** [comment]
@dhh hmm, this is failing for me because it's trying to build and push the image to a private registry. It only works if I use the `--skip-push` flag. Should the redeploy command default to only pulling then?

**Comment by dhh** [comment]
If you’ve deployed once on that machine, you should already be logged into the registry. Then you can do redeploy from there. If that’s not working for some reason, you can also just use deploy every time.

**Comment by tonysm** [comment]
Yeah, I think the issue is because I'm using the alias install, so it runs in a container. The docker client there isn't authenticated. But that's okay, I'll use the deploy cmd or redeploy with the `--skip-push` flag if I need a config change.

**Pull request closed without merging**
