### PR TITLE
Configurable SSH port

### PR DESCRIPTION
**Pull request by leonvogt**
One of the machines I wanted to deploy to had a custom SSH port.   
I think it would be handy if you could easily specify the SSH port, similar to the [SSH user](https://kamal-deploy.org/docs/configuration#using-a-different-ssh-user-than-root).   
This PR would allow a port configuration like this:

```yml
ssh:
  port: 2222
```

### CODE REVIEW

**Review by fahu — APPROVED** [review]

**Comment by djmb** [comment]
Thanks for the PR @leonvogt!

There's one failing test, could you resolve it? 🙏

```
2023-10-30T08:41:42.1135161Z Failure:
2023-10-30T08:41:42.1136000Z MainTest#test_config [/home/runner/work/kamal/kamal/test/integration/main_test.rb:56]:
2023-10-30T08:41:42.1137067Z --- expected
2023-10-30T08:41:42.1137860Z +++ actual
2023-10-30T08:41:42.1138420Z @@ -1 +1 @@
2023-10-30T08:41:42.1139101Z -{:user=>"root", :keepalive=>true, :keepalive_interval=>30, :log_level=>:fatal}
2023-10-30T08:41:42.1140078Z +{:user=>"root", :port=>22, :keepalive=>true, :keepalive_interval=>30, :log_level=>:fatal}
```

**Comment by leonvogt** [comment]
@djmb     
My bad, the integration tests didn't work properly on my machine.   
Should be fixed now.

**Comment by djmb** [comment]
Thanks for the PR @leonvogt! Tests are all passing now.

If you had an insight into why the integrations test don't run for you, I'd be interested to know!

**Comment by djmb** [comment]
One other thing @leonvogt - could you raise a PR on https://github.com/basecamp/kamal-site to document the new setting? 🙏

**Comment by leonvogt** [comment]
> One other thing @leonvogt - could you raise a PR on https://github.com/basecamp/kamal-site to document the new setting? 🙏

Sure thing, I'll do

**Comment by leonvogt** [comment]
> If you had an insight into why the integrations test don't run for you, I'd be interested to know!

It fails at line 7 in the [integration_test](https://github.com/basecamp/kamal/blob/da161445fad1f438cc7365fbb3993186535d05d6/test/integration/integration_test.rb#L7).     
I'll get the following Docker output:
```bash
[...]
Step 10/20 : COPY *.sh .
When using COPY with more than one source file, the destination must be a directory and end with a /
```

The solution for me was to change `COPY *.sh .` to `COPY *.sh ./` in the [Dockerfile](https://github.com/basecamp/kamal/blob/da161445fad1f438cc7365fbb3993186535d05d6/test/integration/docker/deployer/Dockerfile#L19).     
I'm not sure why I had to do this and other people don't. Therefore I didn't open a Issue or PR for that.

**Pull request merged**
