### PR TITLE
Allow lines option to be configured when following app logs

### PR DESCRIPTION
**Pull request by alhafoudh**
Issue: #633

### CODE REVIEW

**Comment by djmb** [comment]
Thanks for the PR @alhafoudh 🙏

I've run the tests locally and I'm getting one error:

```
Failure:
CommandsAppTest#test_follow_logs [/Users/dmcbreen/Work/basecamp/kamal/test/commands/app_test.rb:147]:
Expected /docker\ ps\ \-\-quiet\ \-\-filter\ label=service=app\ \-\-filter\ label=role=web\ \-\-filter\ status=running\ \-\-filter\ status=restarting\ \-\-latest\ \|\ xargs\ docker\ logs\ \-\-timestamps\ \-\-tail\ 10\ \-\-follow\ 2>&1/ to match "ssh -t root@app-1 -p 22 'docker ps --quiet --filter label=service=app --filter label=role=web --filter status=running --filter status=restarting --latest | xargs docker logs --timestamps --follow 2>&1'".


bin/test Users/dmcbreen/Work/basecamp/kamal/test/commands/app_test.rb:146
```

Could you resolve that and then I'll get this merged.

**Comment by alhafoudh** [comment]
@djmb Hi, I ran tests on my machine and I get no errors :( Do you have more error context you can share?

**Comment by alhafoudh** [comment]
@djmb Nevermind, I reproduced the error.

**Comment by alhafoudh** [comment]
@djmb You merged it before I fixed the tests. Sorry for confusion. Here is another PR for the assertion fix: https://github.com/basecamp/kamal/pull/712

**Comment by djmb** [comment]
Hey @alhafoudh - I wanted to get your changes in, so I merged and then committed a fix for the tests after. I'll close your other PR. Thanks again for this!

**Pull request merged**
